#! /usr/bin/python3

import sys
import csv
import argparse

class Attendance:
    def run(config, output):
        file = open(config)
        persondict = Attendance.readPeople(file)

        next = input("Swipe PolyCards...(\"quit\" to finish)\n")
        while next != 'quit' and next != 'exit':
            id = toId(next)

            if id and id in persondict:
                persondict[id].here()
            else:
                print("ID doesn't exist in database")
            next = input()

        file = open(output, "w")
        writer = csv.writer(file)

        for person in sorted(persondict.values()):
            writer.writerow([person.first, person.last, "TRUE" if person.attended else "FALSE"])

    def readPeople(file):
        persondict = {}
        reader = csv.DictReader(file, ['first', 'last', 'id'])

        for person in reader:
            persondict[toId(person['id'])] = Member(person['first'], person['last'])

        return persondict

def toId(code):
    if ';' in code:
        code = code.split(';')[1]
    return code.strip('?')

class Member():
    def __init__(self, first, last):
        self.first = first
        self.last = last
        self.attended = False

    def __lt__(self, other):
        if isinstance(other, Member):
            if self.last == other.last:
                return self.first < other.first
            else:
                return self.last < other.last

    def here(self):
        self.attended = True
        print(self.first + " " + self.last)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("config", help="The name of a .csv file with columns 'First Name', 'Last Name', 'ISO Number'")
    parser.add_argument("output", help="The name of the output .csv file that will have columns 'First Name', 'Last Name', 'Attendance'")
    args = parser.parse_args()
    Attendance.run(args.config, args.output)
